# Generated by Django 2.1.2 on 2019-04-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=25)),
                ('emailid', models.EmailField(max_length=50)),
                ('phoneNo', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
