# Generated by Django 2.1.2 on 2019-04-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190422_2315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peoples',
            table='userData',
        ),
    ]
